import type { Metadata } from "next";
import "./globals.css";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="relative flex size-full min-h-screen flex-col bg-white overflow-x-hidden font-sans">
      <main className="flex-1">{children}</main>
    </div>
       
      </body>
    </html>
  );
}
